[package]
name = "dataflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

[features]
types = []
coordinator = []
